force-app/main/default/objects/Salesforce_Project__c/Salesforce_Project__c.object-meta.xml
<CustomObject>
    <label>Salesforce Project</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In-progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Ticket__c/Salesforce_Ticket__c.object-meta.xml
<CustomObject>
    <label>Salesforce Ticket</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Ticket__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_Ticket__c/fields/Requested_by_date__c.field-meta.xml
<CustomField>
    <fullName>Requested_by_date__c</fullName>
    <label>Requested by date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Salesforce_Ticket__c/fields/Salesforce_Project__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Project__c</fullName>
    <label>Salesforce Project</label>
    <referenceTo>Salesforce_Project__c</referenceTo>
    <relationshipLabel>Salesforce Tickets</relationshipLabel>
    <relationshipName>Salesforce_Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Salesforce_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In development</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DmlDemo2.cls
public class DmlDemo2 {
   public static void dmlUpdateDemo_3() {
       //1. fetch record
       account acc = [select id, name, Site from account where name like 'Soft%' limit 1];
       //2. update account
       acc.Name = 'SoftInnovas Inc.';
       acc.site = 'www.softinnovas.com';

       //3. update DML
       update acc;
       system.debug('acc = ' + acc);
   }

   public static void dmlInsertRelatedDemo_1() {
       //1. fetch account record
       account acc = [select id, name from account where name = 'SoftInnovas Inc.' limit 1];

       //2. create contact's instance
       Contact c = new Contact();
       c.LastName = 'Biden';
       c.AccountId = acc.Id;
       insert c;
   }

   public static void dmlInsertRelatedDemo_2() {
       Salesforce_Project__c sp = [select id, name from Salesforce_Project__c order by CreatedDate DESC limit 1];

       Salesforce_Ticket__c st = new Salesforce_Ticket__c();
       st.Subject__c = 'Learn DML in APEX';
       st.Priority__c = 'High';
       st.Status__c = 'New';
       st.Requested_by_date__c = date.newInstance(2022, 7, 29);
       st.Salesforce_Project__c = sp.id;

       insert st;
       system.debug('st = ' + st);
   }

   public static void dmlInsertMultipleRecord_right1() {
       List<account> listAcc = new list<account>();
       account a = new account();
        a.name = 'bulk acc 1';
        listAcc.add(a);
        account a1 = new account();
        a1.name = 'bulk acc 2';
        listAcc.add(a1);

        account a2 = new account();
        a2.name = 'bulk acc 3';
        listAcc.add(a2);
        account a3 = new account();
        a3.name = 'bulk acc 4';
        listAcc.add(a3);

        insert listAcc;
   }

   public static void dmlMultipleRecordInsert_right2() {
       //1. we create a new LIST<sObject>
       List<account> listAccount = new list<account>();

       for (Integer i = 0; i < 200; i++) {
           account acc = new account();
           acc.name = 'SoftInnovas 29July v'+i;
           acc.AccountNumber = 'Accis-'+i;
           acc.Active__c = 'Yes';
           listAccount.add(acc);
       }

       system.debug('size of list = ' + listAccount.size());
       if (!listAccount.isEmpty()) {
           insert listAccount;
       }
   }
}