force-app/main/default/objects/Salesforce_Project__c/Salesforce_Project__c.object-meta.xml
<CustomObject>
    <label>Salesforce Project</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPTriggerHandlerTest.cls
@isTest
public  class SPTriggerHandlerTest {
    @isTest
    public static void testMethod1() {
        Salesforce_project__c sp = new salesforce_project__c();
        sp.project_name__c = 'Teach DML to falcons';
        sp.description__c = 'All are great learners';

        test.startTest();
        insert sp;
        test.stopTest();

        List<Salesforce_Project__c> listSP = [select id, description__c from Salesforce_Project__c];
        system.assert(listSP[0].Description__c.containsIgnoreCase('future'));
    }
}