force-app/main/default/objects/Salesforce_Project__c/Salesforce_Project__c.object-meta.xml
<CustomObject>
    <label>Salesforce Project</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DmlDemo.cls
public class DmlDemo {
  public static void dmlInsertDemo_stndObj() {
      //1. create new instance
      Account acc = new account();
      //2. set field values
      acc.Name = 'SoftInnovas';
      acc.Active__c = 'Yes';
      //INSERT
      insert acc;
      system.debug(acc);
  }

  public static void dmlInsertDemo_cstmObj() {
      Salesforce_project__c sp = new salesforce_project__c();
      sp.project_name__c = 'Teach DML to falcons';
      sp.description__c = 'All 40% are great learners';
      insert sp;
      system.debug(sp);
  }
}