force-app/main/default/objects/Salesforce_Project__c/Salesforce_Project__c.object-meta.xml
<CustomObject>
    <label>Salesforce Project</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Ticket__c/Salesforce_Ticket__c.object-meta.xml
<CustomObject>
    <label>Salesforce Ticket</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_Ticket__c/fields/Salesforce_Project__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Project__c</fullName>
    <label>Salesforce Project</label>
    <referenceTo>Salesforce_Project__c</referenceTo>
    <relationshipLabel>Salesforce Tickets</relationshipLabel>
    <relationshipName>Salesforce_Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesforceProjectTriggerHandler.cls
public with sharing class SalesforceProjectTriggerHandler {
   public static void createDefaultSalesforceTicket(List<salesforce_project__c> spTriggerNew) {
       //create one empty list of ticket
       List<Salesforce_Ticket__c> newSTList = new List<Salesforce_Ticket__c>();
       for (salesforce_project__c eachSP : spTriggerNew) {
           Salesforce_Ticket__c st = new Salesforce_Ticket__c();
           st.Subject__c = 'Default ST';
           st.Salesforce_Project__c = eachSP.id;
           newSTList.add(st);
       }
       if(!newSTList.isEmpty()){
           insert newSTList;
       }
   }
}